<?php

namespace TitleDK\Calendar\Tests\Colors;

use \SilverStripe\Dev\SapphireTest;
use TitleDK\Calendar\Calendars\Calendar;

class CalendarColorExtensionTest extends SapphireTest
{
    /** @var Calendar */
    private $calendar;

    public function setUp()
    {
        $this->calendar = new Calendar();
        return parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testTextColor()
    {
        $this->assertEquals('', $this->calendar->TextColor());
    }


    public function testGetColorWithHash()
    {
        $this->calendar->Color = '444';
        $this->assertEquals('#444', $this->calendar->getColorWithHash());

        $this->calendar->Color = '#444';
        $this->assertEquals('#444', $this->calendar->getColorWithHash());
    }

    public function testUpdateCMSFields()
    {
        $this->markTestSkipped('TODO');
    }
}
