<?php

namespace TitleDK\Calendar\Tests\Colors;

use \SilverStripe\Dev\SapphireTest;
use TitleDK\Calendar\Calendars\Calendar;

class CalendarColorExtensionTest extends SapphireTest
{
    /** @var Calendar */
    private $calendar;

    public function setUp()
    {
        $this->calendar = new Calendar();
        return parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function test_text_color_dark_bg()
    {
        $this->calendar->Color = '243456';
        $this->assertEquals('#fff', $this->calendar->TextColor());
    }

    public function test_text_color_light_bg()
    {
        $this->calendar->Color = 'DDDAAA';
        $this->assertEquals('#000', $this->calendar->TextColor());
    }

    public function test_get_color_with_hash()
    {
        $this->calendar->Color = 'A48A48';
        $this->assertEquals('#A48A48', $this->calendar->getColorWithHash());

        $this->calendar->Color = '#A48A48';
        $this->assertEquals('#A48A48', $this->calendar->getColorWithHash());
    }

    public function test_update_cms_fields()
    {
        $fields = $this->calendar->getCMSFields()->toArray();
            $names = array_map(function($field) {
                return $field->Name;
            },
            $fields);

            // @todo fix this test
        $this->assertEquals([], $names);
    }
}
