<?php

namespace TitleDK\Calendar\Tests\Colors;

use \SilverStripe\Dev\SapphireTest;
use TitleDK\Calendar\Colors\ColorHelper;

class ColorHelperTest extends SapphireTest
{
    /** @var ColorHelper */
    private $helper;

    public function setUp()
    {
        $this->helper = new ColorHelper();
        return parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function test_light_backgrounds_for_text_color()
    {
        $this->assertEquals('#000', $this->helper->calculate_textcolor('#AABBCC'));
        $this->assertEquals('#000', $this->helper->calculate_textcolor('#FFFFFF'));
        $this->assertEquals('#000', $this->helper->calculate_textcolor('#808080'));
    }

    public function test_dark_backgrounds_for_text_color()
    {
        $this->assertEquals('#fff', $this->helper->calculate_textcolor('#000000'));
        $this->assertEquals('#fff', $this->helper->calculate_textcolor('#444444'));
        $this->assertEquals('#fff', $this->helper->calculate_textcolor('#7F7F7F'));
    }
}
