<?php

namespace TitleDK\Calendar\Tests\Libs;

use \SilverStripe\Dev\SapphireTest;
use TitleDK\Calendar\Calendars\Calendar;

class DoURLSegmentExtensionTest extends SapphireTest
{
    /** @var Calendar */
    private $calendar;

    public function setUp()
    {
        $this->calendar = new Calendar();
        $this->calendar->Title = 'Test Calendar';
        return parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testOnBeforeWrite()
    {
        $this->calendar->write();
        $this->assertEquals('test-calendar', $this->calendar->URLSegment);
    }

    public function testGetLink()
    {
        $this->assertEquals('test-calendar', $this->calendar->getLink());
    }
}
