<?php

namespace TitleDK\Calendar\Tests\Registrations;

use \SilverStripe\Dev\SapphireTest;
use TitleDK\Calendar\Events\Event;

class EventRegistrationTest extends SapphireTest
{
    protected static $fixture_file = 'tests/registered-events.yml';

    /** @var Event */
    private $conference;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->conference = $this->objFromFixture('TitleDK\Calendar\Events\Event', 'conference');
    }

    public function testGetFrontEndFields()
    {
        $this->markTestSkipped('TODO');
    }

    public function testGetRegistrationCode()
    {
        $this->assertEquals(1, $this->conference->Registrations()->count());
    }
}
